DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE ADMINBOARD CASCADE CONSTRAINTS;
DROP TABLE BD_COMMENT CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
DROP TABLE FAVORITE CASCADE CONSTRAINTS;
DROP TABLE MAP CASCADE CONSTRAINTS;
DROP TABLE PICTURE CASCADE CONSTRAINTS;
DROP TABLE STARPOINT CASCADE CONSTRAINTS;
DROP SEQUENCE ADMINBOARD_SEQ;
DROP SEQUENCE BOARD_SEQ;
DROP SEQUENCE FAVORITE_SEQ;
DROP SEQUENCE PICTURE_SEQ;


-- MEMBER Table Create SQL
CREATE TABLE MEMBER
(
    MB_ID            VARCHAR2(20)    NOT NULL, 
    MB_PWD           VARCHAR2(30)    NOT NULL, 
    MB_NAME          VARCHAR2(20)    NOT NULL, 
    MB_EMAIL         VARCHAR2(30)    NOT NULL, 
    MB_GENDER        VARCHAR2(1)     NOT NULL, 
    MB_BIRTHDAY      DATE            NOT NULL, 
    MB_PHONE         VARCHAR2(20)    NOT NULL, 
    MB_JOINDATE      DATE            NOT NULL, 
    MB_MANAGER_YN    VARCHAR2(1)     NOT NULL, 
    CONSTRAINT MEMBER_PK PRIMARY KEY (MB_ID)
)
/


-- CATEGORY Table Create SQL
CREATE TABLE CATEGORY
(
    CG_ID      VARCHAR2(30)    NOT NULL, 
    CG_NAME    VARCHAR2(20)    NOT NULL, 
    CONSTRAINT CATEGORY_PK PRIMARY KEY (CG_ID)
)
/


-- LOCATION Table Create SQL
CREATE TABLE LOCATION
(
    LOC_ID      VARCHAR2(20)     NOT NULL, 
    LOC_NAME    VARCHAR2(100)    NOT NULL, 
    CONSTRAINT LOCATION_PK PRIMARY KEY (LOC_ID)
)
/


-- BOARD Table Create SQL
CREATE TABLE BOARD
(
    BD_NO               NUMBER            NOT NULL, 
    BD_TITLE            VARCHAR2(100)     NOT NULL, 
    BD_CONTENT          VARCHAR2(4000)    NOT NULL, 
    BD_WRITER           VARCHAR2(20)      NOT NULL, 
    BD_ENROLLDATE       DATE              NOT NULL, 
    BD_CATEGORY         VARCHAR2(30)      NOT NULL, 
    BD_LOCATION         VARCHAR2(20)      NOT NULL, 
    BD_COUNT            NUMBER            NOT NULL, 
    BD_COMMENT_COUNT    NUMBER            NOT NULL, 
    BD_STARPOINT        NUMBER            NOT NULL, 
    BD_SINGO            NUMBER            NOT NULL, 
    CONSTRAINT BOARD_PK PRIMARY KEY (BD_NO)
)
/

CREATE SEQUENCE BOARD_SEQ
START WITH 1
INCREMENT BY 1;
/

ALTER TABLE BOARD
    ADD CONSTRAINT FK_BOARD_BD_WRITER_MEMBER_MB_I FOREIGN KEY (BD_WRITER)
        REFERENCES MEMBER (MB_ID)
/

ALTER TABLE BOARD
    ADD CONSTRAINT FK_BOARD_BD_CATEGORY_CATEGORY_ FOREIGN KEY (BD_CATEGORY)
        REFERENCES CATEGORY (CG_ID)
/

ALTER TABLE BOARD
    ADD CONSTRAINT FK_BOARD_BD_LOCATION_LOCATION_ FOREIGN KEY (BD_LOCATION)
        REFERENCES LOCATION (LOC_ID)
/


-- BD_COMMENT Table Create SQL
CREATE TABLE BD_COMMENT
(
    CM_WRITER      VARCHAR2(20)    NOT NULL, 
    CM_BOARD_NO    NUMBER          NOT NULL, 
    CM_CONTENT     VARCHAR2(20)    NOT NULL
)
/

ALTER TABLE BD_COMMENT
    ADD CONSTRAINT FK_BD_COMMENT_CM_WRITER_MEMBER FOREIGN KEY (CM_WRITER)
        REFERENCES MEMBER (MB_ID)
/

ALTER TABLE BD_COMMENT
    ADD CONSTRAINT FK_BD_COMMENT_CM_BOARD_NO_BOAR FOREIGN KEY (CM_BOARD_NO)
        REFERENCES BOARD (BD_NO)
/


-- ADMINBOARD Table Create SQL
CREATE TABLE ADMINBOARD
(
    ADB_TITLE         VARCHAR2(200)     NOT NULL, 
    ADB_NO            NUMBER            NOT NULL, 
    ADB_CONTENT       VARCHAR2(4000)    NOT NULL, 
    ADB_WRITER        VARCHAR2(20)      NOT NULL, 
    ADB_ENROLLDATE    DATE              NOT NULL, 
    ADB_COUNT         NUMBER            NOT NULL, 
    CONSTRAINT ADMINBOARD_PK PRIMARY KEY (ADB_TITLE)
)
/

CREATE SEQUENCE ADMINBOARD_SEQ
START WITH 1
INCREMENT BY 1;
/


ALTER TABLE ADMINBOARD
    ADD CONSTRAINT FK_ADMINBOARD_ADB_WRITER_MEMBE FOREIGN KEY (ADB_WRITER)
        REFERENCES MEMBER (MB_ID)
/


-- STARPOINT Table Create SQL
CREATE TABLE STARPOINT
(
    STP_BOARD_NO    NUMBER    NOT NULL, 
    STP_POINT       NUMBER    NOT NULL, 
    STP_MB_COUNT    NUMBER    NOT NULL, 
    CONSTRAINT STARPOINT_PK PRIMARY KEY (STP_BOARD_NO)
)
/

ALTER TABLE STARPOINT
    ADD CONSTRAINT FK_STARPOINT_STP_BOARD_NO_BOAR FOREIGN KEY (STP_BOARD_NO)
        REFERENCES BOARD (BD_NO)
/


-- PICTURE Table Create SQL
CREATE TABLE PICTURE
(
    PIC_ID               NUMBER           NOT NULL, 
    PIC_BOARD_NO         NUMBER           NOT NULL, 
    PIC_UP_DATE          DATE             NOT NULL, 
    PIC_ORIGINAL_NAME    VARCHAR2(300)    NOT NULL, 
    PIC_RENAME           VARCHAR2(300)    NOT NULL, 
    CONSTRAINT PICTURE_PK PRIMARY KEY (PIC_ID)
)
/

CREATE SEQUENCE PICTURE_SEQ
START WITH 1
INCREMENT BY 1;
/

ALTER TABLE PICTURE
    ADD CONSTRAINT FK_PICTURE_PIC_BOARD_NO_BOARD_ FOREIGN KEY (PIC_BOARD_NO)
        REFERENCES BOARD (BD_NO)
/


-- MAP Table Create SQL
CREATE TABLE MAP
(
    MAP_NO          NUMBER           NOT NULL, 
    MAP_LOCATION    VARCHAR2(100)    NOT NULL, 
    CONSTRAINT MAP_PK PRIMARY KEY (MAP_NO)
)
/

ALTER TABLE MAP
    ADD CONSTRAINT FK_MAP_MAP_NO_BOARD_BD_NO FOREIGN KEY (MAP_NO)
        REFERENCES BOARD (BD_NO)
/


-- FAVORITE Table Create SQL
CREATE TABLE FAVORITE
(
    FA_MB_ID    VARCHAR2(20)    NOT NULL, 
    FA_BD_NO    NUMBER          NOT NULL, 
    FA_ID       NUMBER          NOT NULL
)
/

CREATE SEQUENCE FAVORITE_SEQ
START WITH 1
INCREMENT BY 1;
/

ALTER TABLE FAVORITE
    ADD CONSTRAINT FK_FAVORITE_FA_MB_ID_MEMBER_MB FOREIGN KEY (FA_MB_ID)
        REFERENCES MEMBER (MB_ID)
/

ALTER TABLE FAVORITE
    ADD CONSTRAINT FK_FAVORITE_FA_BD_NO_BOARD_BD_ FOREIGN KEY (FA_BD_NO)
        REFERENCES BOARD (BD_NO)
/

alter table adminboard 
modify (adb_enrolldate default sysdate);

alter table board 
modify (bd_enrolldate default sysdate);

alter table member 
modify (mb_joindate default sysdate);


alter table member
add check (mb_gender in ('M', 'F'));

alter table member 
modify (mb_manager_yn default 'N');

alter table member
add check (mb_manager_yn in ('Y', 'N'));

INSERT INTO LOCATION VALUES(1, '서울특별시');
INSERT INTO LOCATION VALUES(2, '인천광역시');
INSERT INTO LOCATION VALUES(3, '부산광역시');
INSERT INTO LOCATION VALUES(4, '울산광역시');
INSERT INTO LOCATION VALUES(5, '대구광역시');
INSERT INTO LOCATION VALUES(6, '대전광역시');
INSERT INTO LOCATION VALUES(7, '광주광역시');
INSERT INTO LOCATION VALUES(8, '경기도');
INSERT INTO LOCATION VALUES(9, '강원도');
INSERT INTO LOCATION VALUES(10, '충청북도');
INSERT INTO LOCATION VALUES(11, '충청남도');
INSERT INTO LOCATION VALUES(12, '전라북도');
INSERT INTO LOCATION VALUES(13, '전라남도');
INSERT INTO LOCATION VALUES(14, '경상북도');
INSERT INTO LOCATION VALUES(15, '경상남도');
INSERT INTO LOCATION VALUES(16, '제주도');

INSERT INTO CATEGORY VALUES(1, '코스');
INSERT INTO CATEGORY VALUES(2, '맛집');
INSERT INTO CATEGORY VALUES(3, '명소');

COMMIT;
